version: "3.8"


services:

  auth-db:
    container_name: auth-db
    image: postgres

    env_file:
      - service_db/runtime.env

    environment:
      PGDATA: '/var/lib/postgresql/data/pgdata'

    expose:
      - "5432"

    networks:
      remote_code_net:

    labels:
      - "traefik.enable=false"


    volumes:
      - type: bind
        source: ./service_db/db_files
        target: /var/lib/postgresql/data/pgdata

      - type: bind
        source: ./service_db/init_script/
        target: /docker-entrypoint-initdb.d

    restart: unless-stopped


  remote-code-auth:
    container_name: remote-code-auth
    image: remote-code-auth:latest
    build:
      context: ./../
      dockerfile: ./core/Dockerfile


    labels:
      - "traefik.http.routers.auth.rule=Host(`api.remote-code.woldseth.xyz`) && PathPrefix(`/auth/`)"


    expose:
      - "9080"
      - "9443"

    env_file:
      - ./runtime_envs/db_login.env
      - ./runtime_envs/default_users.env

    volumes:
      - type: volume
        source: token_key_storage
        target: /aplication_storage/token_key

    networks:
      - remote_code_net

    depends_on:
      - auth-db

networks:
  remote_code_net:
    external: true

volumes:
  token_key_storage:
